language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - extra-android-m2repository
    - android-23

jdk:
  - oraclejdk8

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "tqhNfhdRBdetQmosxGJWhH3OypHSocCZhHkWSI6SZJxdURnzht7llt1CgBsQH67U3hyYR0rQ+vnRvtR6IAV84930IVHdK57HzN6DC37CtSkBwUm5N+foT+yyqt8mMPViHxukGdvl97KEFd9PVW50JkI7TaDa33C340mMNqpedFm8swqpP9hWzefIeqcRHzQiuL27eIQfbrI3ePr1PE4T3Rrb/Mqnjdmk1AzgqzbstMr9BdlSPBG/amLHYdkFT5yOPUKESvakvLIqZC7tMRiQeddJfXC9JgZ6bULd3gQhCL3sXiyuDZNOomwo7eovkowqXSCt68g0axPc/RrJD8dIZGHubWcuAlpp/Ow4uBTORuBRiWn4VuYiHS7NyXIWj3Iz5Q61ewDxDumlR9rHpFjZjqLnPACVWOakv9NTo1zqFQW2R5NUNwi4UqAp1N5wy7k8zqqCxtAafvBsT5SdyJgXc6pU3/HeqZkaNsr8Q98ElEZwwdXE9Lj5ZmpCe0vgM8Tj9g5CbmLgmr29JYGiFXtOpW08WpiJeKV8fivFMkOmV907P+ctCVgOxT5RjHlzC09pPDwOdthAI9LDlRg5eR3xnSgC9Xt8NuV2YNw9aIwmCqN9Hn1PLLgC9kT2KTDXqYpdmnVkhx5zh+E1i62hHm/0+Mz1VI/OZ7fXaPscwm6wf+w="
    - secure: "B+XqrMz91TqCwAgiS6Q+wNkMWfEKxTI249H3fBXjPhi971lZi8APZCe8taCVF4E0fmyFp57qaWoNGsov3s8V84GkFQIQObDqMAEbTcVliEHDLZzC05uW7WnbWWgDOznYa/YQNNv0R0TvHbNj0J+CtERE3FbthOngGIK6sarKHEludgVSQR2CIZOlLN8pP+HjGRb5kolQQZZuOco4Mm8Ez96hfkIazgH7OMSStVG9KF//h3WgqG91lQ4RnzSkYpHsCcj3hExHW2G2lZTvvByBpoZdONv5T7Xj5MZEMmW5549cVQPySYa0lke4noDc96mPOvw8uUNJXudgYhiey3KejSqsH6RVodF4rnzYVzMBmg2zxGqg+Mi4lq4nDObI6h+49Ff3nOR2u+O/QYdWPptAhzotVCdsk2lPn30djt8xb6pHIRW0ApZqaheYGqG+DDRxsWGDOIMsV4ylgDFBuvUQRmkFFfSNTYwylznH2JBClnAhVa3ZX1pPqXKx3N20y7arR5e4uiqDajA3/gjPKNMKMLCzJ4isPxa3pAYeUTPhqiM/kv5P4/sEd3SxqnUax+4ZvFdodv52KWJxx7/Iqbi2/rdKKCeRpPwFDw8/AO7HFtLTbg81bcRBylbvTplOe5XGa4PgBbEVrFJtvTb6midj21EEr9DyVBjzPeSfSpu/Yq8="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false
